# Generated by Django 3.0 on 2021-03-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="supervisor",
            field=models.BooleanField(default=False),
        ),
    ]
