# Generated by Django 3.0 on 2021-05-04 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 18, 48, 43, 793964)),
        ),
        migrations.AddField(
            model_name='user',
            name='student_number',
            field=models.CharField(default='C000000', max_length=7),
        ),
    ]
