# Generated by Django 3.0 on 2021-05-04 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210504_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(default=datetime.datetime(2021, 5, 4, 18, 50, 43, 744390)),
        ),
    ]
